### ISSUE TITLE
Older version of tools are used. Need to update version of all tools 

### ISSUE THREAD

**Issue by vaibhavp** [alpine-docker/k8s#1]
HELM_VERSION=2.14.3 --> 3.2.0
KUBECTL_VERSION=1.13.10 --> 1.18.2
AWS_IAM_AUTH_VERSION=0.4.0 --> 0.5.0

**Comment by ozbillwang** [comment]
This image is built for AWS EKS only, currently it doesn't support v1.18

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
