### ISSUE TITLE
build fail at helm-unittest

### ISSUE THREAD

**Issue by ozbillwang** [alpine-docker/k8s#15]
after merge #12 and #14, the build is failed at `helm-unittest` in tag `1.19.8`

```
Step 11/19 : RUN helm plugin install https://github.com/quintush/helm-unittest && rm -rf /tmp/helm-*
 ---> Running in e0c1e7fbb23d
Support linux-amd64
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/latest
No download_url found only searching for linux
Downloading https://github.com/quintush/helm-unittest/releases/download/v0.2.6/helm-unittest-linux-amd64-0.2.6.tgz https://github.com/quintush/helm-unittest/releases/download/v0.2.6/helm-unittest-linux-arm64-0.2.6.tgz to location /tmp/_dist/
curl: (3) URL using bad/illegal format or missing URL
Error: plugin install hook for "unittest" exited with error
Failed to install helm-unittest
```

and `kubeseal` not found

cc: @gaima8

**Comment by gaima8** [comment]
I'm thinking this is a problem with travis.

1.19.8 couldn't find the version of kubeseal and the install of helm-unittest failed
1.18.9 couldn't find the version of kustomize or kubeseal, helm-unittest did install
1.17.12 worked fine
1.16.15 worked fine too
1.15.12 also worked fine

Enabling `set -e` would be a good idea, the build should fail if anything fails.

**Comment by ozbillwang** [comment]
@gaima8 

yes, I have the same feeling. 

I trigger a small change, and rebuild the images. Now it looks fine. Both 1.19.8 and 1.18.9 are fine now.

Thanks

**Comment by ozbillwang** [comment]
And I have added `set -e` in build script 👍
