### ISSUE TITLE
add latest tag to docker image

### ISSUE THREAD

**Issue by jamestupper** [alpine-docker/k8s#16]
can a `latest` tag be added to the docker image, so `docker pull alpine/k8s` works correctly. this is the current output of that command:

```
C:\Users\james.tupper> docker pull alpine/k8s
Using default tag: latest
Error response from daemon: manifest for alpine/k8s:latest not found: manifest unknown: manifest unknown
```

**Comment by ozbillwang** [comment]
this repo and its images are not for kuberentes latest. 

it is used for EKS deployment, which only support the version AWS EKS supported

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

So latest tag doesn't make sence.
