### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by allinonedashboard** [alpine-docker/k8s#18]
Hello,

I used the alpine/k8s image. Getting the below error.
![image](https://user-images.githubusercontent.com/50626781/123067948-5ae9d480-d409-11eb-8445-ed81b0d725ac.png)

Error: The connection to the server localhost:8080 was refused - did you specify the r
ight host or port?

Expected Output: able to see the list of services in the cluster
can you help me what i am missing here?

**Comment by ozbillwang** [comment]
In your ~/.kube/config it's api server is set to localhost, but when you run helm in docker, the localhost is helm's container.

You can update to your laptop's IP.
