### ISSUE TITLE
AWS EKS 1.21 release

### ISSUE THREAD

**Issue by Sebor** [alpine-docker/k8s#20]
Hello!
What about version 1.21.2?
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Comment by Sebor** [comment]
Suggested PR #22

**Comment by Sebor** [comment]
Hmm, but component version are still old: https://app.travis-ci.com/github/alpine-docker/k8s/jobs/526545593

**Comment by ozbillwang** [comment]
and closed by #23 with enhancements
