### ISSUE TITLE
Can't pull alpine/k8s from docker hub

### ISSUE THREAD

**Issue by jwsomis** [alpine-docker/k8s#21]
When trying to pull alpine/k8s from docker hub image is not found.

```
$ docker pull alpine/k8s
Using default tag: latest
Error response from daemon: manifest for alpine/k8s:latest not found: manifest unknown: manifest unknown
```

**Comment by jwsomis** [comment]
I am able to pull specific versions, so it's just for latest

**Comment by Sebor** [comment]
> I am able to pull specific versions, so it's just for latest

There is no "latest" tag in repo. It is by design
