### ISSUE TITLE
Weekly (nor nightly) build not published

### ISSUE THREAD

**Issue by kbkk** [alpine-docker/k8s#27]
The README mentions a weekly build:
```
### Weekly build

Build job runs weekly
```

Yet there's been no release at Dockerhub for the past 3 months.
The latest changes in GitHub render the image unusable due to a stale `openssh` version:
```
error cloning repository: unknown error: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.
```

**Comment by ozbillwang** [comment]
this repo is used for AWS EKS deployment. 

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

![image](https://user-images.githubusercontent.com/8954908/149013324-062b5b27-4763-4d3f-90de-b016fa940bbb.png)

If there is no new version, it runs the build, but ignore to build to save the build time (these free cicd pipeline has limits time to be used)

but for the openssh issue, I need run time to duplicate the problem. Can you share detail about this error?

**Comment by kbkk** [comment]
> but for the openssh issue, I need run a check to duplicate the problem. Can you share detail about this error?

Sorry for the vague description. Starting today, GitHub will require OpenSSH >=7.2 https://github.blog/2021-09-01-improving-git-protocol-security-github/ causing this error message:
```
error cloning repository: unknown error: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.
```

I checked again and this in fact is a problem with CircleCI providing an old SSH client, as this image doesn't include `openssh` at all. 
Sorry for the inconvenience. Closing.
