### ISSUE TITLE
Adding yq as the sibling to jq

### ISSUE THREAD

**Issue by exocode** [alpine-docker/k8s#28]
I saw that `jq` is implemented. I have a script like the following, which extracts a kubeconfig which is bas64 enconded. In that kubeconfig I've to extract the server address, but that is only possible with yq.

I thought if `jq` is a wrench in the toolbox, why not `yq`? :-)

Is this possible to add?

`kubectl get secret cluster-details-staging -o jsonpath="{.data.kubeconfig}"  | base64 -d | yq e ".clusters[0].cluster.server" -`

**Comment by ozbillwang** [comment]
not bid deal, please raise a PR for it.
