### ISSUE TITLE
kubeseal broken, download URL needs to be fixed in Dockerfile

### ISSUE THREAD

**Issue by 7oku** [alpine-docker/k8s#32]
kubeseal is not working in the latest images (we tested with `alpine/k8s:1.22.10`):

```
/ # kubeseal
/usr/bin/kubeseal: line 1: Not: not found
```

That is because kubeseal seems to have renamed their binary releases and also packaged them into an tar.gz. During build of the docker image curl is not being able to fetch it correctly and stores the 404 `Not found` in the file.

The old curl expanded to: 
```
curl -sL https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.1/kubeseal-li
nux-amd64 -o kubeseal
```

but should now expand to something like
```
curl -L https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.1/kubeseal-0.1
8.1-linux-amd64.tar.gz -o - | tar xz -C /usr/bin/
```

**Comment by ozbillwang** [comment]
thanks to report this issue. can you raise the PR to fix?
