### ISSUE TITLE
Use latest aws-iam-authenticator

### ISSUE THREAD

**Issue by rofreytag** [alpine-docker/k8s#35]
Hello there!

Can you please update aws-iam-authenticator to the latest version for your next releases? (aws-iam-authenticator_0.5.9).

When running 

```
docker run -it --rm alpine/k8s:1.22.10 aws-iam-authenticator version
```

I get 

```
{"Version":"v0.5.0","Commit":"1cfe2a90f68381eacd7b6dcfa2bf689e76eb8b4b"}
```

It may be that AWS is not hosting the correct image at this URL:

    s3://amazon-eks/1.23.9/2022-07-27/bin/linux/amd64/aws-iam-authenticator

We are currently getting the latest from this URL

    https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64

Much appreciated!

**Comment by ozbillwang** [comment]
Can you raise the pull request?

**Comment by rofreytag** [comment]
done
