### ISSUE TITLE
kubectl broken in latest builds

### ISSUE THREAD

**Issue by sr258** [alpine-docker/k8s#36]
It looks like `kubectl` is not built into the latest builds correctly. I get

```
/usr/bin/kubectl: line 1: syntax error: unexpected redirection
```

when I run kubectl. The file in `/usr/bin/kubectl` contains:

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.23/bin/linux/amd64/kubectl</Details></Error>/apps 
```

**Comment by rltvty** [comment]
I'm also seeing this...

**Comment by jralph** [comment]
I was able to get this working again by using a specific version (eg, `alpine/k8s:1.22.10` instead of `alpine/k8s:1.22`).

**Comment by ozbillwang** [comment]
let me check. Seems the latest 4 tags build 7 days before are broken, and the new tags are not sementic versioning as well. 

But there is change recently in last 7 days.

**Comment by ozbillwang** [comment]
ok, the source document has some changes

https://raw.githubusercontent.com/awsdocs/amazon-eks-user-guide/master/doc_source/kubernetes-versions.md

![image](https://user-images.githubusercontent.com/8954908/191258283-d162717f-dd85-4e19-bc6f-e793206b70e0.png)

**Comment by ozbillwang** [comment]
I cleaned the last 5 tags (1.19, 1.20, 1.21, 1.22, 1.23) , stopped the nightly schedule job ,  until this problem can be fixed.

**Comment by ozbillwang** [comment]
Updates will be done:

1. Don't stick on AWS EKS supported versions any more
2. Version reference page will be changed from [Amazon EKS Kubernetes versions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html) to [kubernetes Release History](https://kubernetes.io/releases/)
3. only target on most recent minor releases
