### ISSUE TITLE
Update Helm Unittest repository

### ISSUE THREAD

**Issue by Angelin01** [alpine-docker/k8s#49]
[Quintush](https://github.com/quintush/) has taken over the [official repository for Helm Unittest](https://github.com/helm-unittest/helm-unittest), see issue https://github.com/quintush/helm-unittest/issues/124 and [release v0.3.0](https://github.com/helm-unittest/helm-unittest/releases/tag/v0.3.0).

As such, this line:
https://github.com/alpine-docker/k8s/blob/d2e35a959d7358f6f74be234da94fa7430926067/Dockerfile#L24
can probably start pointing to the new repository.

**Comment by ozbillwang** [comment]
sure, will you be fine to raise the pull request?

**Comment by Angelin01** [comment]
PR opened: https://github.com/alpine-docker/k8s/pull/50
