### ISSUE TITLE
the last version not working. missed value for `ARG AWS_IAM_AUTH_VERSION_URL`

### ISSUE THREAD

**Issue by Gershon-A** [alpine-docker/k8s#6]
Hello,
the last version not working.
Seem here is missed value for `ARG AWS_IAM_AUTH_VERSION_URL`
I adding it as following and all work
```
ARG AWS_IAM_AUTH_VERSION_URL="https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/aws-iam-authenticator"
```

**Comment by ozbillwang** [comment]
ARG in Dockerfile is optional, if don't feed the value, it will use the default one. 

My script will handle the `AWS_IAM_AUTH_VERSION_URL` automatically when new version released

      build --no-cache --build-arg KUBECTL_VERSION=${tag} --build-arg HELM_VERSION=${helm} --build-arg AWS_IAM_AUTH_VERSION_URL="${iam_auth_url}" -t ${image}:${tag} .


Please provide the detail, on which tag which image do you have issue.

**Comment by Gershon-A** [comment]
Sorry for the late response.
I used `docker pull alpine/k8s:1.13.12`

**Comment by ozbillwang** [comment]
I can 

```
$ docker run -ti --rm alpine/k8s:1.13.12 aws-iam-authenticator version
{"Version":"v0.5.0","Commit":"1cfe2a90f68381eacd7b6dcfa2bf689e76eb8b4b"}
```

**Comment by Gershon-A** [comment]
The problem occurs when I build the repo locally
``` ---> 6c09b9fd4407
Step 9/13 : RUN curl -LO ${AWS_IAM_AUTH_VERSION_URL} &&     mv aws-iam-authenticator /usr/bin/aws-iam-authenticator &&     chmod +x /usr/bin/aws-iam-authenticator
 ---> Running in cabcb827ec9c
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
The command '/bin/sh -c curl -LO ${AWS_IAM_AUTH_VERSION_URL} &&     mv aws-iam-authenticator /usr/bin/aws-iam-authenticator &&     chmod +x /usr/bin/aws-iam-authenticator' returned a non-zero code: 2```

**Comment by ozbillwang** [comment]
I see. You try to `docker build` by yourself. but it doesn't work as this way. 

The design for this repo is, 

1. travis CI defines the kubernetes version in [.travis.yml](.travis.yml)

```
env:
  - tag=1.18.2
  - tag=1.17.5
  - tag=1.16.8
  - tag=1.15.11
  - tag=1.14.9
  - tag=1.13.12
```
2. script [build.sh](build.sh) will get the latest version of AWS IAM Auth, helm, and rest tools. 

3. Travis CI will trigger the build daily to run the script [build.sh](build.sh) 

So if you want to reuse this repo to build your own image, you can do this way:

```
export tag=1.13.12

bash ./build.sh
```

**Comment by ozbillwang** [comment]
I have updated the [README.md](README.md) for your concern. 

https://github.com/alpine-docker/k8s/blob/master/README.md#involve-with-developing-and-testing

**Comment by Gershon-A** [comment]
Thank You!
