### ISSUE TITLE
Compatibility of Helm with K8s

### ISSUE THREAD

**Issue by gendergap** [alpine-docker/k8s#60]
I tried out the image version `1.20.15` (because that matches my cluster) and found that this contains Helm in version `3.9.3`. According to [this matrix](https://helm.sh/docs/topics/version_skew/) the correct Helm versions for Kubernetes 1.20 would be 3.5 to 3.8, not 3.9. Is this intentionally "incompatible" in this image?

**Comment by ozbillwang** [comment]
Thanks for the url of the matrix. Currently the builds don't follow it up. 

Current way, when new version of kubectl (latest supported 4 minor versions) is realased, the images will be built with latest helm version.
