### ISSUE TITLE
Missing colordiff as external diff for kubectl

### ISSUE THREAD

**Issue by jromelague** [alpine-docker/k8s#66]
Hi,

It would be nice if this image would contain the [colordiff](https://pkgs.alpinelinux.org/package/edge/community/armhf/colordiff) tool in order to be used as an external diff for the kubectl command.

Best regards.

**Comment by ozbillwang** [comment]
This image has [helm-diff](https://github.com/databus23/helm-diff) (latest commit) already. 

Second, I went through its homepage (please confirm we are talking about the same tool): https://www.colordiff.org/

![image](https://github.com/alpine-docker/k8s/assets/8954908/45364500-ff6a-4c39-af50-91e6fa3d3077)

it needs perl, which I prefer Golang binary to keep the image size small.

**Comment by jromelague** [comment]
helm-diff is for helm chart.
When the kubernetes resources I want to apply is not managed by an helm chart, I use kubectl and I always have in my CIs a diff stage before applying the changes to see what would be applied.
kubectl have a diff command but does not manage colors in diff. I use the `KUBECTL_EXTERNAL_DIFF="colordiff -N -u"` environment variable with colordiff https://www.colordiff.org/ to have a better output.
