### ISSUE TITLE
Latest versions are not working

### ISSUE THREAD

**Issue by MZohaibAsaad** [alpine-docker/k8s#7]
Hello. 
I was using this image in gitlab pipelines and it broke two days ago. It gives me error when i'm trying to connect to k8s cluster.
Command i ran:
`kubectl apply --kubeconfig=kubeconfig.yaml --filename https://github.com/knative/serving/releases/download/v0.14.0/serving-crds.yaml`
Error i got:
`unable to recognize "https://github.com/knative/serving/releases/download/v0.14.0/serving-crds.yaml": Get https://server.region.eks.amazonaws.com/api?timeout=32s: getting credentials: exec: fork/exec /usr/bin/aws-iam-authenticator: exec format error`

And strange thing is that i tried to replicate the issue on local machine by ssh into local docker image and running above command but it ran just fine inside local docker image, but same thing fails in pipeline.

**Comment by ozbillwang** [comment]
seems you run something in AWS EKS, please check your setting in it. 

Seems it blocked your external access to github.com.

**Comment by thapakazi** [comment]
@ozbillwang This is a issue, I just execed inside the container 
![screenshot-20200818-14:08:52](https://user-images.githubusercontent.com/1695906/90488947-5d7dfc80-e15c-11ea-94a6-4d9166ab06a0.png)
 and found iam-authenticator is broken.

It broke my CI :(

**Comment by ozbillwang** [comment]
which tag?

**Comment by thapakazi** [comment]
Hey @ozbillwang, I think you could just rebuild it once again on travis, build.sh its working with new iam binary for me in local.

This job is weird though: https://travis-ci.org/github/alpine-docker/k8s/jobs/718664972
 
![screenshot-20200818-15:36:27](https://user-images.githubusercontent.com/1695906/90498991-b358a180-e168-11ea-86c6-f3f2102fba36.png)

I wonder why build.sh pulled this url: https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-07-08/bin/linux/amd64/aws-iam-authenticator

**Comment by thapakazi** [comment]
New [build](https://travis-ci.org/github/alpine-docker/k8s/jobs/718902281) worked from me @ozbillwang :+1:

**Comment by ozbillwang** [comment]
try now

**Comment by ozbillwang** [comment]
the aws-iam-auth url is coming from this document: 

https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html

AWS doesn't share us the go through permission that we can't know what's the latest version from above url

https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-08-04/bin/linux/amd64/aws-iam-authenticator

I used some scripts to catch the keyword about `1.17.9/2020-08-04`, but seems aws developers are keep changing the html format. The build.sh is failed to get the latest version of "aws-iam-auth"

**Comment by thapakazi** [comment]
Hmm could be, I thought the same too, I was thinking of trying alternative, directly from github like:
```
latest_aws_iam_auth=$(curl https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/latest | sed -r 's/.*http.*v(.*)">.*/\1/')
AWS_IAM_AUTH_VERSION_URL=https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v${latest_aws_iam_auth}/aws-iam-authenticator_${latest_aws_iam_auth}_linux_amd64
```

**Comment by ozbillwang** [comment]
I used to get the latest release from github, but I found they are different.
