### ISSUE TITLE
Add AWS CLI v2

### ISSUE THREAD

**Issue by chetankapoor** [alpine-docker/k8s#9]
Hey,

It would be great if you can add AWS CLI v2 in the docker image. Currently, it is having awscli v1.18.*

**Comment by ozbillwang** [comment]
Good suggestions. 

Could we have both installed? I knew still a lot of users are use aws cli v1 currently.

**Comment by ozbillwang** [comment]
by the way, seems it is hard to install aws cli v2 in Alpine

https://github.com/aws/aws-cli/issues/4971

**Comment by ozbillwang** [comment]
close this issue, that I am not going to support aws cli v2.
